### ISSUE TITLE
Crash with index out of range

### ISSUE THREAD

**Issue by KrolikPDX** [jmp/poker-hand-evaluator-swift#1]
When trying to get the value of 
[6♦, 7♦, 8♦, A❤, A♠]
which is set as:
Hand([
    Card(.six, .diamonds),
    Card(.seven, .diamonds),
    Card(.eight, .diamonds),
    Card(.ace, .hearts),
    Card(.ace, .spades)])

The value function crashes at line 26 in Hand.swift:
<img width="1149" alt="Screen Shot 2021-04-06 at 3 09 13 PM" src="https://user-images.githubusercontent.com/48137744/113784300-0e380c80-96ea-11eb-90eb-90d94cd3038a.png">

Here is a sample code that will cause it to crash in any initialized class:
    init() {
        let testHand =
            Hand([
                Card(.six, .diamonds),
                Card(.seven, .diamonds),
                Card(.eight, .diamonds),
                Card(.ace, .hearts),
                Card(.ace, .spades)])
        print("Attempting to test hand: \(testHand)")
        print("Value of test hand: \(testHand.value)")
    }

Using the testHand above, it will keep crashing with pairs of Aces, Kings, Queens, and Jacks in combination with a backdoor straight draw (i.e. 6-8). However; once we reach a pair of Tens it successfully gets the value of the hand. If we remove the backend straight draw it will also work. Suits do not seem to have an impact on the issue. 

The library was imported through XCode by going to File>Swift Packages>Add Package Dependency... followed by the URL of this project.

**Comment by jmp** [comment]
Thanks for the report! This should be fixed now in `master`.

Turns out there were two problems, one was the "index out of range" issue. After fixing that I noticed that I'm also getting an arithmetic overflow for example with with cards 6-8 and two kings. The reason was because I used Swift's `Int` type for almost everything which is 64-bit signed integer on most systems. That broke the hashing part as you saw. I've fixed it now to use 32-bit unsigned integers instead.
